name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions: 
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      
      - name: Build
        run: |
          cd frontend
          npm install
          npm run build
          cd ..
          wails build -platform windows -o BitcoinUSBWallet
      
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: build/bin/BitcoinUSBWallet.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
      
      - name: Build
        run: |
          cd frontend
          npm install
          npm run build
          cd ..
          wails build -platform darwin -o BitcoinUSBWallet
      
      - name: Create DMG
        run: |
          brew install create-dmg
          create-dmg \
            --volname "Bitcoin USB Wallet" \
            --window-pos 200 120 \
            --window-size 600 400 \
            --icon-size 100 \
            --app-drop-link 400 185 \
            "BitcoinUSBWallet.dmg" \
            "build/bin/"
      
      - name: Upload Mac Build  
        uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: BitcoinUSBWallet.dmg

  release:
    needs: [build-windows, build-mac]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: windows-exe
          path: release
      
      - uses: actions/download-artifact@v4
        with:
          name: mac-dmg
          path: release
      
      - name: Check files
        run: ls -la release/
      
      - uses: softprops/action-gh-release@v2
        with:
          files: release/*
          body: |
            ## Bitcoin USB Wallet Release
            
            ### 다운로드
            - Windows: `BitcoinUSBWallet.exe`
            - macOS: `BitcoinUSBWallet.dmg`